### ISSUE TITLE
Getting run time exception : TypeError: 'SRCDELIMITER' is an invalid keyword argument for this function

### ISSUE THREAD

**Issue by ahmedmohiduet** [cschnaars/FEC-Scraper-Toolbox#5]
A part of my logs giving:
processing...  168192.fec
Traceback (most recent call last):
  File "parse_reports.py", line 4471, in <module>
    filehdr = parse_data_row(filehdr, SRCDELIMITER)
  File "parse_reports.py", line 485, in parse_data_row
    for x in csv.reader([data], SRCDELIMITER=',', quotechar='"'):
TypeError: 'SRCDELIMITER' is an invalid keyword argument for this function

Am I missing something here!

**Comment by mindcrime** [comment]
I just started getting this as well.  I have no idea why, as nothing has changed with my setup AFAIK.  Weird.

**Comment by mindcrime** [comment]
OK, I don't understand quite what happened here. The Git log doesn't show any recent changes and this worked for me like 3 days ago.  But I poked around in the code, and made the following change and it seems to be working now.

`[centos@ip-172-31-27-206 FEC-Scraper-Toolbox]$ git diff parse_reports.py 
diff --git a/parse_reports.py b/parse_reports.py
index 9f00528..640f32b 100644
--- a/parse_reports.py
+++ b/parse_reports.py
@@ -460,7 +460,7 @@ def parse_data_row(data, delim):
     # be joined together and the parsing to fail. For that reason, I'm
     # using csv module only for comma delimiters.
     if delim == ',':
-        for x in csv.reader([data], SRCDELIMITER=',', quotechar='"'):
+        for x in csv.reader([data], delimiter=SRCDELIMITER, quotechar='"'):
             data = x
     else:
         data = data.split(delim)
[centos@ip-172-31-27-206 FEC-Scraper-Toolbox]$ 
`

**Comment by mindcrime** [comment]
Wait, I think I may know what is happening.  I was running this before with no errors, and just now I saw this error for the first time.  At first I thought nothing had changed, but I just realized that I changed my download date range to include 1 more year of history than previously.  I went from grabbing everything from Jan 1 2009 to now, to grabbing everything from Jan 1 2008 to now.  I suspect the 2008 data is different, and this is causing the problem.

**Comment by mindcrime** [comment]
I'm re-running my download/processing now, will update this if I can definitely identify what's going on.
